/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Util.AdminArchivos;
import Util.AdminSerializacion;
import clases.*;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dennis2
 */
public class FrmBoleto extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmLibro
     */
    private int _indiceSeleccion;
    private boolean _agregando;

    public FrmBoleto() {
        initComponents();
        this.setTitle("Gestión de Boletos");
        try {
            actualizarElementosTabla();
        } catch (Exception e) {
        }

        try {
            this.cboCategVuelo.setModel(MDIPrincipal.gCateg.getCboModel());
        } catch (Exception e) {
        }
        try {
            this.cboAerolinea.setModel(MDIPrincipal.gAero.getCboModel());
        } catch (Exception e) {
        }
        try {
            this.cboOrigen.setModel(MDIPrincipal.gOrigen.getCboModel());
        } catch (Exception e) {
        }
        try {
            this.cboDestino.setModel(MDIPrincipal.gDestino.getCboModel());
        } catch (Exception e) {
        }
        try {
            this.cboAsiento.setModel(MDIPrincipal.gAsiento.getCboModel());
        } catch (Exception e) {
        }
        try {
            this.cboFecha.setModel(MDIPrincipal.gFecha.getCboModel());
        } catch (Exception e) {
        }
        try {
            this.cboHoraAbordaje.setModel(MDIPrincipal.gHora.getCboModel());
        } catch (Exception e) {
        }
        try {
            this.cboNumPuerta.setModel(MDIPrincipal.gNPuerta.getCboModel());
        } catch (Exception e) {
        }
        try {
            this.cboPasajero.setModel(MDIPrincipal.gPasajero.getCboModel());
        } catch (Exception e) {
        }

    }

    public void estadoBotones(boolean _estado) {
        this.btnBuscar.setEnabled(_estado);
        this.btnEditar.setEnabled(_estado);
        this.btnEliminar.setEnabled(_estado);
        this.btnGuardar.setEnabled(!_estado);
        this.btnNuevo.setEnabled(_estado);
        this.btnSalir.setEnabled(_estado);
        this.btnReporte.setEnabled(_estado);
    }

    public void estadoCombos(boolean _estado) {
        this.cboAerolinea.setEnabled(_estado);
        this.cboAsiento.setEnabled(_estado);
        this.cboCategVuelo.setEnabled(_estado);
        this.cboDestino.setEnabled(_estado);
        this.cboFecha.setEnabled(_estado);
        this.cboHoraAbordaje.setEnabled(_estado);
        this.cboNumPuerta.setEnabled(_estado);
        this.cboOrigen.setEnabled(_estado);
        this.cboPasajero.setEnabled(_estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboOrigen = new javax.swing.JComboBox<>();
        cboDestino = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cboPasajero = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboNumPuerta = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboHoraAbordaje = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboFecha = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cboCategVuelo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cboAsiento = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cboAerolinea = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtBoleto = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();

        jLabel2.setText("Ciudad de Origen:");

        jLabel7.setText("Ciudad de Destino:");

        cboOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboOrigen.setEnabled(false);

        cboDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDestino.setEnabled(false);

        jLabel8.setText("Pasajero:");

        cboPasajero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPasajero.setEnabled(false);
        cboPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPasajeroActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero de Puerta:");

        cboNumPuerta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNumPuerta.setEnabled(false);

        jLabel4.setText("Hora de Abordaje:");

        cboHoraAbordaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboHoraAbordaje.setEnabled(false);
        cboHoraAbordaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHoraAbordajeActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha:");

        cboFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboFecha.setEnabled(false);

        jLabel6.setText("Categoria de Vuelo:");

        cboCategVuelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCategVuelo.setEnabled(false);

        jLabel9.setText("Asiento:");

        cboAsiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboAsiento.setEnabled(false);

        jLabel10.setText("Aerolinea:");

        cboAerolinea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboAerolinea.setEnabled(false);

        jtBoleto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtBoleto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtBoletoMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtBoleto);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        txtCodigo.setEditable(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cboCategVuelo, javax.swing.GroupLayout.Alignment.LEADING, 0, 160, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboFecha, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(btnReporte))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(cboOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel10)
                                                .addComponent(cboAerolinea, 0, 160, Short.MAX_VALUE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel9)
                                                .addComponent(cboAsiento, 0, 160, Short.MAX_VALUE))
                                            .addComponent(jLabel3)
                                            .addComponent(cboNumPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnNuevo)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEditar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBuscar))
                                            .addComponent(jLabel4)
                                            .addComponent(cboHoraAbordaje, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnEliminar))
                                                .addGap(18, 18, 18)
                                                .addComponent(btnGuardar)))))
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir)))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btnReporte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCategVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboNumPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboHoraAbordaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnEditar)
                    .addComponent(btnBuscar)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalir)
                    .addComponent(btnGuardar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPasajeroActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        _agregando = true;
        this.txtCodigo.setText("");

        estadoBotones(false);
        estadoCombos(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (_indiceSeleccion >= 0) {
            int resultado = JOptionPane.showConfirmDialog(null, "¿Está seguro?", "Warning", JOptionPane.YES_NO_OPTION);
            if (resultado == JOptionPane.YES_OPTION) {
                MDIPrincipal.gBoleto.Eliminar(_indiceSeleccion);
                actualizarElementosTabla();
                //Paso 6: Serializar informacion
                AdminSerializacion.serializacion(MDIPrincipal.gBoleto, "gPasajero.obj");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Favor seleccione el elemento de la tabla que desea eliminar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        /**
         * 1. Solicitar valores 2. Crear instancia 3. Setear valores a instancia
         * 4. Agregar instancia a la gestion 5. Mostrar valores
         */

        //Paso 1 Solicitar valores
        String codigo;
        codigo = this.txtCodigo.getText();

        CategVuelo _categVuelo = MDIPrincipal.gCateg.getElementoPorPosicion(this.cboCategVuelo.getSelectedIndex());
        Aerolinea _aerolinea = MDIPrincipal.gAero.getElementoPorPosicion(this.cboAerolinea.getSelectedIndex());

        Asiento _asiento = MDIPrincipal.gAsiento.getElementoPorPosicion(this.cboAsiento.getSelectedIndex());
        Origen _origen = MDIPrincipal.gOrigen.getElementoPorPosicion(this.cboOrigen.getSelectedIndex());
        Destino _destino = MDIPrincipal.gDestino.getElementoPorPosicion(this.cboDestino.getSelectedIndex());
        NumPuerta _numPuerta = MDIPrincipal.gNPuerta.getElementoPorPosicion(this.cboNumPuerta.getSelectedIndex());
        Fecha _fecha = MDIPrincipal.gFecha.getElementoPorPosicion(this.cboFecha.getSelectedIndex());
        HoraAbordaje _horaAbordaje = MDIPrincipal.gHora.getElementoPorPosicion(this.cboHoraAbordaje.getSelectedIndex());
        Pasajero _pasajero = MDIPrincipal.gPasajero.getElementoPorPosicion(this.cboPasajero.getSelectedIndex());

        try {
            //Paso 2 Crear instancia
            Boleto _boleto = new Boleto();

            //Paso 3 Setear valores a instancia
            _boleto.set_categoriaVuelo(_categVuelo);
            _boleto.set_aerolinea(_aerolinea);
            _boleto.set_asiento(_asiento);
            _boleto.set_destino(_destino);
            _boleto.set_fecha(_fecha);
            _boleto.set_horaAbordaje(_horaAbordaje);
            _boleto.set_numPuerta(_numPuerta);
            _boleto.set_origen(_origen);
            _boleto.set_pasajero(_pasajero);

            //Paso 4 Agregar instancia a la gestion
            if (_agregando) {
                MDIPrincipal.gBoleto.Agregar(_boleto);
            } else { //Editara
                //Paso 1.1
                codigo = this.txtCodigo.getText();
                //Paso 3.1
                _boleto.set_codigo(Integer.parseInt(codigo));

                MDIPrincipal.gBoleto.Modificar(_indiceSeleccion, _boleto);
            }

            //Paso 5 Mostrar valores
            actualizarElementosTabla();

            AdminSerializacion.serializacion(MDIPrincipal.gBoleto, "gBoleto.obj");
            estadoBotones(true);
            estadoCombos(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar" + e.getMessage());
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String _codigoBoleto = JOptionPane.showInputDialog("Ingrese el código");
        Boleto _BoletoEncontrado = MDIPrincipal.gBoleto.BuscarPorIdGetElem(Integer.parseInt(_codigoBoleto));
        if (_BoletoEncontrado == null) {
            JOptionPane.showMessageDialog(this, "Elemento no encontrado");
        } else {
            mostrarElemento(_BoletoEncontrado);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        _agregando = false;
        estadoBotones(false);
        estadoCombos(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void cboHoraAbordajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHoraAbordajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboHoraAbordajeActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        AdminArchivos adminA = new AdminArchivos();
        adminA.setNombreArchivo("Reporte Boleto.csv");
        adminA.setContenido(MDIPrincipal.gBoleto.getInfoReporte());
        adminA.escribir();
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(this, "Reporte generado correctamente");
    }//GEN-LAST:event_btnReporteActionPerformed

    private void jtBoletoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtBoletoMousePressed
        // TODO add your handling code here:
        _indiceSeleccion = jtBoleto.getSelectedRow();
        if (_indiceSeleccion != -1) {
            Boleto _boleto = MDIPrincipal.gBoleto.getElementoPorPosicion(_indiceSeleccion);
            mostrarElemento(_boleto);
        }
    }//GEN-LAST:event_jtBoletoMousePressed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    public void mostrarElemento(Boleto _boleto) {
        this.txtCodigo.setText(Integer.toString(_boleto.get_codigo()));
        int _indice;
        Pasajero _pasajero = _boleto.get_pasajero();
        _indice = MDIPrincipal.gPasajero.BuscarPorId(_pasajero.get_codigo());
        this.cboPasajero.setSelectedIndex(_indice);

        Origen _origen = _boleto.get_origen();
        _indice = MDIPrincipal.gOrigen.BuscarPorcodigo(_origen.get_codigo());
        this.cboOrigen.setSelectedIndex(_indice);

        Destino _destino = _boleto.get_destino();
        _indice = MDIPrincipal.gDestino.BuscarPorcodigo(_destino.get_codigo());
        this.cboDestino.setSelectedIndex(_indice);

        NumPuerta _numpuerta = _boleto.get_numPuerta();
        _indice = MDIPrincipal.gNPuerta.BuscarPorcodigo(_numpuerta.get_codigo());
        this.cboNumPuerta.setSelectedIndex(_indice);

        HoraAbordaje _horaAbordaje = _boleto.get_horaAbordaje();
        _indice = MDIPrincipal.gHora.BuscarPorcodigo(_horaAbordaje.get_codigo());
        this.cboHoraAbordaje.setSelectedIndex(_indice);

        Fecha _fecha = _boleto.get_fecha();
        _indice = MDIPrincipal.gFecha.BuscarPorcodigo(_fecha.get_codigo());
        this.cboFecha.setSelectedIndex(_indice);

        CategVuelo _categVuelo = _boleto.get_categoriaVuelo();
        _indice = MDIPrincipal.gCateg.BuscarPorId(_categVuelo.get_codigo());
        this.cboCategVuelo.setSelectedIndex(_indice);

        Asiento _asiento = _boleto.get_asiento();
        _indice = MDIPrincipal.gAsiento.BuscarPorcodigo(_asiento.get_codigo());
        this.cboAsiento.setSelectedIndex(_indice);

        Aerolinea _aerolinea = _boleto.get_aerolinea();
        _indice = MDIPrincipal.gAero.BuscarPorcodigo(_aerolinea.get_codigo());
        this.cboAerolinea.setSelectedIndex(_indice);

    }

    public void actualizarElementosTabla() {
        // String codigo, pasajero, origen, destino, puerta, hora, fecha, categoria, asiento, aerolinea
        String[] titulos = {"Código", "Pasajero", " Origen", " Destino", " Número de Puerta", " Hora de Abordaje", " Fecha", " Categoria de Vuelo", " Número de Asiento", " Aerolinea"};
        DefaultTableModel dt = new DefaultTableModel(MDIPrincipal.gBoleto.GetArrayGestion(), titulos);
        this.jtBoleto.setModel(dt);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboAerolinea;
    private javax.swing.JComboBox<String> cboAsiento;
    private javax.swing.JComboBox<String> cboCategVuelo;
    private javax.swing.JComboBox<String> cboDestino;
    private javax.swing.JComboBox<String> cboFecha;
    private javax.swing.JComboBox<String> cboHoraAbordaje;
    private javax.swing.JComboBox<String> cboNumPuerta;
    private javax.swing.JComboBox<String> cboOrigen;
    private javax.swing.JComboBox<String> cboPasajero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtBoleto;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
