/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Util.AdminFechas;
import Util.AdminSerializacion;
import clases.*;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pinedas
 */
public class FrmFacturacionBoletos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmFacturacion
     */
    public static boolean _agregando;
    private Date _fecha;
    public int _codigoFactura;
    private Cliente _clienteFactura;
    private AsesorServ _asesorServFactura;
    private Boleto _boletoFactura;
    private Aerolinea _aerolineaFactura;
    private Factura _facturaEncontrada;
    private int _posicionFactura;
    private int _posicionDetalle;

    public FrmFacturacionBoletos() {
        initComponents();
        this.setTitle("Facturando Boletos");

    }

    public void inicioFormulario() {
        _fecha = AdminFechas.getFechaActual();
        if (this._agregando) {
            this._codigoFactura = MDIPrincipal.gFactura.GenerarIdFactura();
            lblFecha.setText(AdminFechas.FechaToString(_fecha));
        } else {
            _facturaEncontrada = MDIPrincipal.gFactura.BuscarPorIdGetElem(_codigoFactura);
            actualizarElementosTabla();
        }

        this.lblNoFactura.setText(Integer.toString(_codigoFactura));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNoFactura = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblAsesor = new javax.swing.JLabel();
        btnBuscarAsesor = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAerolinea = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFacturacionBoletos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarBoleto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtPrecioBoleto = new javax.swing.JTextField();
        txtBoleto = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Número de Factura:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(403, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(lblNoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(232, 232, 232));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Factura", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setText("Cliente:");

        jLabel6.setText("Asesor:");

        btnBuscarAsesor.setText("...");
        btnBuscarAsesor.setToolTipText("Buscar Asesor");
        btnBuscarAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsesorActionPerformed(evt);
            }
        });

        btnBuscarCliente.setText("...");
        btnBuscarCliente.setToolTipText("Buscar Cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha:");

        jLabel8.setText("Aerolinea:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarCliente))
                    .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarAsesor))
                    .addComponent(lblAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(btnBuscarAsesor)
                    .addComponent(btnBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtFacturacionBoletos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtFacturacionBoletos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtFacturacionBoletosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtFacturacionBoletos);

        jPanel3.setBackground(new java.awt.Color(232, 232, 232));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Boleto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel4.setText("Boleto:");

        btnBuscarBoleto.setText("...");
        btnBuscarBoleto.setToolTipText("Buscar Boleto");
        btnBuscarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBoletoActionPerformed(evt);
            }
        });

        jLabel10.setText("Precio Venta:");

        txtPrecioBoleto.setEditable(false);

        txtBoleto.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarBoleto)
                        .addGap(207, 207, 207)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecioBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(txtBoleto))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnBuscarBoleto)
                    .addComponent(jLabel10)
                    .addComponent(txtPrecioBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEliminar, btnGuardar, btnSalir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalir))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEliminar, btnGuardar, btnSalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        String _codigoCliente = JOptionPane.showInputDialog(this, "Código del cliente");

        _clienteFactura = MDIPrincipal.gCliente.BuscarPorcodigoGetElem(Integer.parseInt(_codigoCliente));

        if (_clienteFactura != null) {
            this.lblCliente.setText(_clienteFactura.get_nombre() + " " + _clienteFactura.get_apellido());
        } else {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Elemento no encontrado");
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBoletoActionPerformed
        // TODO add your handling code here:
        String _codigoBoleto = JOptionPane.showInputDialog(this, "Código del Boleto");

        _boletoFactura = MDIPrincipal.gBoleto.BuscarPorIdGetElem(Integer.parseInt(_codigoBoleto));

        if (_boletoFactura != null) {
            this.txtBoleto.setText("Código: " + _boletoFactura.get_codigo()
                    + " / " + _boletoFactura.get_pasajero().get_nombre()
                    + " " + _boletoFactura.get_pasajero().get_apellido()
                    + " / " + _boletoFactura.get_origen().get_descripcion()
                    + " / " + _boletoFactura.get_destino().get_descripcion()
                    + " / " + _boletoFactura.get_categoriaVuelo().get_descripcion()
                    + " / " + _boletoFactura.get_horaAbordaje().get_descripcion()
                    + " / " + _boletoFactura.get_fecha().get_descripcion()
            );

            this.txtPrecioBoleto.setText(Integer.toString(_boletoFactura.get_categoriaVuelo().get_precio()));
            _aerolineaFactura = _boletoFactura.get_aerolinea();
            this.txtAerolinea.setText(_aerolineaFactura.get_descripcion());
        } else {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Elemento no encontrado");
        }

    }//GEN-LAST:event_btnBuscarBoletoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        _facturaEncontrada = MDIPrincipal.gFactura.BuscarPorIdGetElem(_codigoFactura);
        if (_facturaEncontrada == null) { //Si no existe, se registrara
            if (_clienteFactura == null) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Ingrese el código del cliente");
            } else {
                if (_asesorServFactura == null) {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "Ingrese el código del asesor");
                } else {
                    if (_boletoFactura == null) {
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(this, "Ingrese el código del boleto");
                    } else {
                        btnBuscarAsesor.setEnabled(false);
                        btnBuscarCliente.setEnabled(false);

                        _facturaEncontrada = new Factura();
                        _facturaEncontrada.set_id(_codigoFactura);
                        _facturaEncontrada.set_aerolinea(_aerolineaFactura);
                        _facturaEncontrada.set_asesorServ(_asesorServFactura);
                        _facturaEncontrada.set_cliente(_clienteFactura);
                        _facturaEncontrada.set_fecha(AdminFechas.FechaToString(_fecha));
                        MDIPrincipal.gFactura.Agregar(_facturaEncontrada);

                    }
                }
            }

        }
        _posicionFactura = MDIPrincipal.gFactura.BuscarPorId(_facturaEncontrada.get_id());
        DetalleFactura _nuevoDetalle = new DetalleFactura();
        _nuevoDetalle.set_boleto(_boletoFactura);
        _nuevoDetalle.set_subtotal(_boletoFactura.get_categoriaVuelo().get_precio());

        boolean _resultado = _facturaEncontrada.agregarDetalle(_nuevoDetalle);
        _facturaEncontrada.set_subtotal(_facturaEncontrada.ObtenerSubTotal());
        _facturaEncontrada.set_isv(_facturaEncontrada.ObtenerSubTotal_ISV());
        _facturaEncontrada.set_total(_facturaEncontrada.ObtenerTotal());
        MDIPrincipal.gFactura.Modificar(_posicionFactura, _facturaEncontrada);
        MDIPrincipal.frmFacturacion.actualizarElementosTabla();
        AdminSerializacion.serializacion(MDIPrincipal.gFactura, "gFactura.obj");
        actualizarElementosTabla();


    }//GEN-LAST:event_btnGuardarActionPerformed

    public void actualizarElementosTabla() {
        String[] titulos = {"Pasajero", "Origen // Destino", "Categoria de Vuelo", "Asiento", "SubTotal"};

        DefaultTableModel dt = new DefaultTableModel(this._facturaEncontrada.getArrayDetalleFactura(), titulos);

        this.jtFacturacionBoletos.setModel(dt);
    }

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        try {
            limpiarFormulario();
        } catch (Exception e) {
        }
        this.dispose();
        //limpiarFormulario();
        btnBuscarCliente.setEnabled(true);
        btnBuscarAsesor.setEnabled(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            if (_posicionDetalle >= 0) {
                int resultado = JOptionPane.showConfirmDialog(null, "¿Está seguro?", "Warning", JOptionPane.YES_NO_OPTION);
                if (resultado == JOptionPane.YES_OPTION) {
                    MDIPrincipal.gFactura.getLstFactura().get(_posicionFactura).Eliminar(_posicionDetalle);
                    actualizarElementosTabla();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Favor seleccione el elemento de la tabla que desea eliminar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jtFacturacionBoletosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFacturacionBoletosMousePressed
        // TODO add your handling code here:
        _posicionDetalle = jtFacturacionBoletos.getSelectedRow();
        if (_posicionDetalle != -1) {
            _posicionFactura = MDIPrincipal.gFactura.BuscarPorId(Integer.parseInt(lblNoFactura.getText()));
            DetalleFactura _detalle = this._facturaEncontrada.obtenerDetallePorPosicion(_posicionFactura);
            //mostrarElemento(_facturaEliminar);
        }
    }//GEN-LAST:event_jtFacturacionBoletosMousePressed

    private void btnBuscarAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAsesorActionPerformed

        String _codigoAsesorServ = JOptionPane.showInputDialog(this, "Código del Asesor");

        _asesorServFactura = MDIPrincipal.gAsesor.BuscarPorcodigoGetElem(Integer.parseInt(_codigoAsesorServ));

        if (_asesorServFactura != null) {
            this.lblAsesor.setText(_asesorServFactura.get_nombre() + " " + _asesorServFactura.get_apellido());
        } else {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Elemento no encontrado");
        }

    }//GEN-LAST:event_btnBuscarAsesorActionPerformed

    private void limpiarFormulario() {
        _boletoFactura = null;
        _clienteFactura = null;
        _asesorServFactura = null;
        this.lblAsesor.setText("");
        this.lblCliente.setText("");
        this.txtBoleto.setText("");
        this.txtAerolinea.setText("");
        this.txtPrecioBoleto.setText("");

        DefaultTableModel model = (DefaultTableModel) jtFacturacionBoletos.getModel();
        model.setRowCount(0);
    }

    /*public void pruebaDialogo() {
        JOptionPane jOprueba = new JOptionPane(
                "The only way to close this dialog is by\n"
                + "pressing one of the following buttons.\n"
                + "Do you understand?",
                JOptionPane.QUESTION_MESSAGE,
                JOptionPane.YES_NO_OPTION
        );

        JOptionPane.showMessageDialog(this, MDIPrincipal.frmFacturacionBoletos);
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAsesor;
    private javax.swing.JButton btnBuscarBoleto;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtFacturacionBoletos;
    private javax.swing.JLabel lblAsesor;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNoFactura;
    private javax.swing.JLabel txtAerolinea;
    private javax.swing.JTextField txtBoleto;
    private javax.swing.JTextField txtPrecioBoleto;
    // End of variables declaration//GEN-END:variables
}
